name: Check PR for Changelog

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  check-pr-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Fields
        id: check_fields
        run: .\.github\workflows\changelog_pr_fields.sh  #run the script
         